
## Step 1: Download data from OpenStreetMap (optional)

# Process OSM data
location_folder : "voz"
location_image: "voz.png"


## Step 2 : Data extraction and processing from OpenStreetMap

resized_location_image : "voz_resized.png"

custom_start_goal : False

# This is hardcoded start and goal position and applied only if custom_start_goal is False
start_longitude: 14.576700
start_latitude : 45.235964

goal_longitude: 14.584563
goal_latitude : 45.229204

## Step 3: Path planning algorithms testing

result_image : "voz_result.png"
table_name : "runtime_results.png"

grid_size : 10.0  # [m]
robot_radius : 5.0  # [m]


# thread_enable : True - thread for plotting map
# thread_enable map : False - for algorithm runtime calculation
thread_enable : False

#test and plot options
# 1. a_star
# 2. bidirectional_a_star
# 3. dijkstra
# 4. d_star
# 5. d_star_lite
# 6. breadth_first_search
# 7. bidirectional_breadth_first_search
# 8. depth_first_search
# 9. greedy_best_first_search

test_algorithm : 
#- "a_star"
#- "bidirectional_a_star"
#- "dijkstra"
#- "d_star"
- "d_star_lite"
#- "breadth_first_search"
#- "bidirectional_breadth_first_search"
#- "greedy_best_first_search"


plot_algorithms:
- "a_star"
- "bidirectional_a_star"
- "dijkstra"
- "d_star"
- "d_star_lite"
- "breadth_first_search"
- "bidirectional_breadth_first_search"
- "greedy_best_first_search"

## Step 4: Cost map generation
result_costmap_name : "voz_costmap.png"
cost_map : False






