## Step 1.1: Download data from OpenStreetMap (optional)

# Process OSM data
location_folder : "voz"


## Step 1.2. : Data extraction and processing from OpenStreetMap 
custom_start_goal : True

# This is hardcoded start and goal position and applied only if custom_start_goal is False
start_latitude : 45.234781
start_longitude: 14.577538

goal_latitude : 45.230241
goal_longitude: 14.583173

grid_size : 10.0  # [m]
robot_radius : 5.0  # [m]

# thread_enable : True - thread for plotting map
# thread_enable map : False - for algorithm runtime calculation
thread_enable : False

#test and plot options
# 1. a_star
# 2. bidirectional_a_star
# 3. dijkstra
# 4. d_star
# 5. d_star_lite
# 6. breadth_first_search
# 7. bidirectional_breadth_first_search
# 8. depth_first_search
# 9. greedy_best_first_search

test_algorithms :
- "a_star"
- "bidirectional_a_star"
- "dijkstra"
- "d_star"
- "d_star_lite"
- "breadth_first_search"
- "bidirectional_breadth_first_search"
- "greedy_best_first_search"



