start_image_name : "voz.png"
start_image_name_bw :  "voz_bw.png"
image_save : "voz_resized.png"
image_save_bw : "voz_bw_resized.png"
# Results
table_name : "test.png"
result_image_name : "result_image.png"

grid_size : 10.0  # [m]
robot_radius : 1.0  # [m]

#test and plot options
# 1. a_star
# 2. bidirectional_a_star
# 3. dijkstra
# 4. d_star
# 5. d_star_lite
# 6. breadth_first_search
# 7. bidirectional_breadth_first_search
# 8. depth_first_search
# 9. greedy_best_first_search

test_algorithm : 
- "a_star"
- "bidirectional_a_star"
- "dijkstra"
- "d_star"
- "d_star_lite"
- "breadth_first_search"
- "bidirectional_breadth_first_search"
- "depth_first_search"
- "greedy_best_first_search"


plot_algorithms:
- "a_star"
#- "bidirectional_a_star"
#- "dijkstra"
- "d_star"
#- "d_star_lite"
#- "breadth_first_search"
#- "bidirectional_breadth_first_search"
#- "depth_first_search"
#- "greedy_best_first_search"


# thread_enable : True - thread for plotting map
# thread_enable map : False - for algorithm runtime calculation
thread_enable : False

costume_start_goal : True



