float32[] start
float32[] goal
---
float32[] path_x
float32[] path_y
float32[] raw_path_x
float32[] raw_path_y
float32 path_distance
float32 raw_path_distance
float32 estimated_path_time
float32 estimated_raw_path_time
---
float32[] partial_path_x
float32[] partial_path_y
float32[] search_area_x
float32[] search_area_y

